import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import prompts from 'prompts';
import ora from 'ora';

const defaultConfig = {
  // Network settings
  rpc: {
    url: 'http://localhost:8545',
    ws: 'ws://localhost:8545',
    timeout: 30000
  },
  
  // Server settings
  server: {
    port: 3000,
    host: 'localhost',
    open: true
  },
  
  // Chain settings
  chain: {
    id: 31337,
    name: 'Localhost',
    currency: 'ETH'
  },
  
  // Feature flags
  features: {
    promotions: false,
    sponsors: false,
    cloudCTA: false
  },
  
  // UI settings
  ui: {
    theme: 'light',
    title: 'Local Blockchain Explorer',
    logo: null
  },
  
  // Advanced settings
  advanced: {
    cacheEnabled: true,
    cacheTTL: 5000,
    maxBlocksPerPage: 25,
    maxTransactionsPerPage: 25,
    enableWebsocket: true
  }
};

export async function init(options) {
  const configPath = path.resolve('./evmscan.config.json');
  
  // Check if config already exists
  if (fs.existsSync(configPath) && !options.force) {
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: 'Configuration file already exists. Overwrite?',
      initial: false
    });
    
    if (!overwrite) {
      console.log(chalk.yellow('⚠️  Configuration unchanged'));
      return;
    }
  }
  
  let config = { ...defaultConfig };
  
  if (!options.quiet) {
    console.log(chalk.blue('\n🔧 Let\'s configure your blockchain explorer\n'));
    
    const responses = await prompts([
      {
        type: 'text',
        name: 'rpcUrl',
        message: 'RPC endpoint URL',
        initial: defaultConfig.rpc.url,
        validate: value => {
          try {
            new URL(value);
            return true;
          } catch {
            return 'Please enter a valid URL';
          }
        }
      },
      {
        type: 'number',
        name: 'port',
        message: 'Server port',
        initial: defaultConfig.server.port,
        validate: value => value > 0 && value < 65536 ? true : 'Please enter a valid port number'
      },
      {
        type: 'number',
        name: 'chainId',
        message: 'Chain ID',
        initial: defaultConfig.chain.id
      },
      {
        type: 'text',
        name: 'chainName',
        message: 'Chain name',
        initial: defaultConfig.chain.name
      },
      {
        type: 'confirm',
        name: 'openBrowser',
        message: 'Open browser automatically?',
        initial: defaultConfig.server.open
      },
      {
        type: 'confirm',
        name: 'enableWebsocket',
        message: 'Enable WebSocket connection for real-time updates?',
        initial: defaultConfig.advanced.enableWebsocket
      }
    ]);
    
    // Apply responses to config
    if (responses.rpcUrl) {
      config.rpc.url = responses.rpcUrl;
      // Auto-generate WebSocket URL if HTTP URL is provided
      if (responses.rpcUrl.startsWith('http://')) {
        config.rpc.ws = responses.rpcUrl.replace('http://', 'ws://');
      } else if (responses.rpcUrl.startsWith('https://')) {
        config.rpc.ws = responses.rpcUrl.replace('https://', 'wss://');
      }
    }
    
    if (responses.port) config.server.port = responses.port;
    if (responses.chainId) config.chain.id = responses.chainId;
    if (responses.chainName) config.chain.name = responses.chainName;
    if (typeof responses.openBrowser !== 'undefined') config.server.open = responses.openBrowser;
    if (typeof responses.enableWebsocket !== 'undefined') config.advanced.enableWebsocket = responses.enableWebsocket;
  }
  
  // Save configuration
  const spinner = ora('Creating configuration file').start();
  
  try {
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    spinner.succeed('Configuration saved to evmscan.config.json');
    
    console.log(chalk.green('\n✅ Setup complete!\n'));
    console.log(chalk.gray('To start the explorer, run:'));
    console.log(chalk.cyan('  evmscan start\n'));
    
    // Also create a .env.local file for the features
    const envPath = path.resolve('./.env.local');
    const envContent = `# evmscan.org configuration
# Generated by evmscan init

# Network Configuration
VITE_RPC_URL=${config.rpc.url}
VITE_WS_URL=${config.rpc.ws}
VITE_CHAIN_ID=${config.chain.id}
VITE_CHAIN_NAME=${config.chain.name}

# Feature Flags
VITE_ENABLE_PROMOTIONS=${config.features.promotions}
VITE_ENABLE_SPONSORS=${config.features.sponsors}
VITE_ENABLE_CLOUD_CTA=${config.features.cloudCTA}
`;
    
    fs.writeFileSync(envPath, envContent);
    
  } catch (error) {
    spinner.fail('Failed to create configuration');
    console.error(chalk.red('Error:'), error.message);
    process.exit(1);
  }
}